### ISSUE TITLE
Code conventies

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/lose-your-head-the-client-case#147]
> - Issue #7 hebben we al besproken welke code conventies we hebben. Hieronder kan je zien wat we hebben afgesproken. 
  > - Klopt dit alleen nog? 
  > - Is onze code volgens deze code conventies?

## `HTML`
* Zo min mogelijk `div` gebruiken
* Goede semantische objecten gebruiken

## `CSS`
* Maak de css code `DRY`. Dus eerst de basiselementen stijlen, waarna je de classes stijlt
* Wanneer je meerdere objecten aanroept, er een enter tussen elk object komt 
```css
p,
ul,
li,
button {
    font-family: var(--font-sans-serif);
    font-size: 1.1em;
    line-height: 1.5em;
}
```
* Wanneer je gebruik maakt van een `@media-query` gebruikt, de waarde binnen het object zet en niet onderaan het bestand. 
Zo moet je het dus niet doen.

https://github.com/SamaraFellaDina/pleasurable-ui/blob/83b0d5311269e8d1128cffbc9cd704a81ab2b71a/public/style.css#L227-L238

maar zo: 

```css
header {
    background-color: var(--primary-color-3);
    border-bottom: var(--border-style-black);
    width: 100%;

  @media (min-width: 768px) {
        border-bottom: none;
}
```

* Het zoveel mogelijk gebruiken van custom properties, waarin je deze ook in kleinere elementen aanroept

### Naamgeving
* Wanneer je een class aanroept, geeft de volgende naamgeving. 
* Maak gebruik van de `BEM` methode. Hierbij geef je de code de volgende naamgeving:
  * Je doet dus `onderwerp` + `object`
```css
.header-search_form
```
  
## `JS`
* naamgeving: Maak gebruik van `CamelCase`
 

 _Originally posted by @SamaraFellaDina in [#7](https://github.com/SamaraFellaDina/lose-your-head-the-client-case/issues/7#issuecomment-2373222740)_
