### ISSUE TITLE
Maken van code conventies

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/lose-your-head-the-client-case#7]
# Aanpak van coderen 
* Wij werken allemaal in eigen component, om zo pull-requests conflicten te voorkomen.
* Geen comments achterlaten bij de commit van je werk.
* In het Engels coderen, dus Engelse naamgeving.

# Manier van coderen
## `CSS`
* **Geen** `css-nesting`
* teksten geven wij de waarde `em`, overig geven wij `px`
* Maak je code `DRY` ;)
* Geen RGB maar HEX

## `JS`
* Gebruik maken van `CamelCase`

## `HTML`
* Gebruik zo min mogelijk `div`s
* Gebruik een logische naamgeving
  * lowercase naamgeving
  * gebruik streepjes
  * naamgeving = `onderwerp` + `onderdeel`
    * Zoals: `.header-sidemenu`

**Comment by Khdulkadir** [comment]
-Met branches werken (naam + onderwerp)
-CamelCase Javascript
-Lower case class names
-Beschrijvende class names

**Comment by SamaraFellaDina** [comment]
## `HTML`
* Zo min mogelijk `div` gebruiken
* Goede semantische objecten gebruiken

## `CSS`
* Maak de css code `DRY`. Dus eerst de basiselementen stijlen, waarna je de classes stijlt
* Wanneer je meerdere objecten aanroept, er een enter tussen elk object komt 
```css
p,
ul,
li,
button {
    font-family: var(--font-sans-serif);
    font-size: 1.1em;
    line-height: 1.5em;
}
```
* Wanneer je gebruik maakt van een `@media-query` gebruikt, de waarde binnen het object zet en niet onderaan het bestand. 
Zo moet je het dus niet doen.

https://github.com/SamaraFellaDina/pleasurable-ui/blob/83b0d5311269e8d1128cffbc9cd704a81ab2b71a/public/style.css#L227-L238

maar zo: 

```css
header {
    background-color: var(--primary-color-3);
    border-bottom: var(--border-style-black);
    width: 100%;

  @media (min-width: 768px) {
        border-bottom: none;
}
```

* Het zoveel mogelijk gebruiken van custom properties, waarin je deze ook in kleinere elementen aanroept

### Naamgeving
* Wanneer je een class aanroept, geeft de volgende naamgeving. 
* Maak gebruik van de `BEM` methode. Hierbij geef je de code de volgende naamgeving:
  * Je doet dus `onderwerp` + `object`
```css
.header-search_form
```
  
## `JS`
* naamgeving: Maak gebruik van `CamelCase`
